# Generated by Django 3.0.4 on 2020-04-18 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fakereview', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentmodel',
            name='text',
            field=models.TextField(max_length=5000),
        ),
    ]
